### ISSUE TITLE
聊天室增加悄悄话功能

### ISSUE THREAD

**Issue by fanyuecheng** [tonquer/picacg-windows#85]

**Comment by tonquer** [comment]
以支持

**Comment by fanyuecheng** [comment]
原来悄悄话不仅要带@悄悄话和@哔咔_name，还要加block_user_id，难怪我这一直返回此人不支援悄悄话😂😂😂

**Comment by tonquer** [comment]
是的 我还以为这个字段是禁言呢，抓包发现悄悄话要带这个



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 中午12:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [tonquer/picacg-windows] 聊天室增加悄悄话功能 (Issue #85)





 
原来悄悄话不仅要带@悄悄话和@哔咔_name，还要加block_user_id，难怪我这一直返回此人不支援悄悄话😂😂😂
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
